# Generated by Django 3.1.1 on 2020-10-07 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikingclub', '0004_booking_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_item', to='hikingclub.hiking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
